verhoeven2021replication
ReScience/RC-2020 pull request #33
Opened 2021-04-23 10:04 UTC by IvoOVerhoeven

Sorry for the late commit, we've had plenty of issues with compilation on our side. Unfortunately, we never managed to get $make to work, and instead compiled in the provided overleaf project: https://www.overleaf.com/read/cbmrrhbwsmtd
I've edited the metadata.tex file according to what's present in the yaml file.

2021-04-23 23:13 UTC, koustuvsinha reviewed
Please fix the paths of images to relative paths `../openreview`

2021-04-23 23:13 UTC, koustuvsinha commented on verhoeven2021replication/openreview/content.tex
> +        \includegraphics[width=.9\textwidth]{openreview/pictures/Figure3/alpha_1.png}
The compilation issues are due to the incorrect file path. When you compile using `make` from the `journal` folder, the latex compiler should expect the relative path of `../openreview/pictures/Figure3/alpha_1.png`. Please fix all the relative paths and then run `make` from journal folder.

2021-04-24 08:24 UTC, IvoOVerhoeven commented
I changed all the image paths, openreview compiles locally, make still not working.

2021-04-25 16:22 UTC, koustuvsinha commented on verhoeven2021replication/openreview/content.tex
> +        \includegraphics[width=.9\textwidth]{openreview/pictures/Figure3/beta_1.png}
Not all paths are changed yet, which results in compilation failure

2021-04-25 16:22 UTC, koustuvsinha commented on verhoeven2021replication/openreview/content.tex
> +        \includegraphics[width=.9\textwidth]{openreview/pictures/Figure3/alpha_1.png}
Still not changed it seems

2021-04-27 12:31 UTC, IvoOVerhoeven commented
The correct openreview/content file should have been pushed now

2021-04-28 21:04 UTC, koustuvsinha commented
Compilation fails: 

```
Latexmk: Missing input file: '../openreview/ablation study 034/InformationFlow.png' from line
  'LaTeX Warning: File `../openreview/ablation study 034/InformationFlow.png' not found on input line 231.'
```

Most probably the folder names are an issue here. Can you change the folder names to a "_" delimited name instead of space? Eg, convert `ablation study 034` to `ablation_study_034`

2021-04-28 21:07 UTC, koustuvsinha commented on verhoeven2021replication/journal/metadata.yaml
> +    affiliations: 1
Please add a '*' (separated by comma) in the affiliations if you are the primary contact. 

```
affiliations: 1,*
```

2021-04-29 21:33 UTC, IvoOVerhoeven commented
Directory names should all have underscores now

2021-05-01 00:18 UTC, koustuvsinha commented
@IvoOVerhoeven Thanks! please also add the contact author information ('*') for the build to compile.

2021-05-01 11:54 UTC, IvoOVerhoeven commented
I've made some small edits to the metadata file, but the contact author * should already be present in the metadata file.

2021-05-04 04:05 UTC, koustuvsinha requested changes

2021-05-04 04:05 UTC, koustuvsinha commented on verhoeven2021replication/journal/metadata.yaml
> +    affiliations: 1, *
remove the space between 1, and *

2021-05-04 04:05 UTC, koustuvsinha commented on verhoeven2021replication/journal/metadata.yaml
> +authors:
This yaml is malformed. `authors` is a list, which contains objects. You have created multiple `authors` lists.. please remove this line (as `authors` list is defined in L12)

2021-05-04 04:05 UTC, koustuvsinha commented on verhoeven2021replication/journal/metadata.yaml
> +authors:
please remove this line (as `authors` list is defined in L12)

2021-05-04 04:05 UTC, koustuvsinha commented on verhoeven2021replication/journal/metadata.yaml
> +authors:
please remove this line (as `authors` list is defined in L12)

2021-05-05 21:14 UTC, IvoOVerhoeven commented
Edits have been made

2021-05-05 23:34 UTC, koustuvsinha commented
Looks good to me! Compiles correctly now.
@sashavor can you review the contents of the paper?

2021-05-05 23:35 UTC, koustuvsinha approved these changes

2021-05-20 18:05 UTC, koustuvsinha commented
@IvoOVerhoeven while going over the contents of the paper I realize you have not added the Reproducibility Summary in the first page. Please add it as soon as possible.

2021-05-24 03:53 UTC, koustuvsinha commented
@IvoOVerhoeven please act on this asap!

2021-05-24 10:50 UTC, IvoOVerhoeven commented
Sorry about that, we initially had it as an abstract. The summary should be on the first 2 pages now without large page gaps in the report.

2021-05-24 19:36 UTC, koustuvsinha requested changes
In your last commit you re-introduced two errors which we fixed before:
1. relative paths (../openreview)
2. folder names.

Please check again.

2021-05-24 19:36 UTC, koustuvsinha commented on verhoeven2021replication/openreview/content.tex
> +		\includegraphics[width=.9\textwidth]{openreview/pictures/Figure3/alpha_1.png}
Why did you re-introduce the bug? I thought we discussed this.

2021-05-24 19:36 UTC, koustuvsinha commented on verhoeven2021replication/openreview/content.tex
> +		\includegraphics[width=.9\textwidth]{openreview/ablation study 034/AblationAccuracy.png}
Why did you re-introduce the folder naming bug? I thought we discussed this.

2021-05-25 14:07 UTC, IvoOVerhoeven commented
I've rolled it back to the last accepted version except for the addition of the summary.

2021-05-25 22:54 UTC, koustuvsinha approved these changes
Thank you, compilation works now and paper has all necessary components.

2021-05-25 22:54 UTC, merged